[tox]
min_version = 4.4.11
envlist = docs,lint,py35,py36,py37,py38,py311

[testenv]
deps =
	-r{toxinidir}/requirements/test.txt
changedir = {envtmpdir}
setenv =
	COLUMNS=80
commands =
	coverage run --rcfile={toxinidir}/.coveragerc --parallel -m unittest discover {toxinidir}/tests
	ln -sf {toxinidir}/samples
	env LANG=C {toxinidir}/bin/clitest --prefix 3 {toxinidir}/tests/cli_tests/hwp5proc.txt {toxinidir}/tests/cli_tests/hwp5odt.txt {toxinidir}/tests/cli_tests/hwp5html.txt {toxinidir}/tests/cli_tests/hwp5txt.txt
allowlist_externals =
	env
	ln

[testenv:docs]
changedir = {toxinidir}
deps =
	-r{toxinidir}/requirements/docs.txt
allowlist_externals =
	make
commands =
	make -C docs html latexpdf

[testenv:lint]
changedir = {toxinidir}
deps =
	-r{toxinidir}/requirements/lint.txt
commands =
	check-manifest
	pyroma .
	flake8 src
